### ISSUE TITLE
Store User's Twitter Data to Loklak

### ISSUE THREAD

**Issue by prasht63** [loklak/loklak_server#64] opened 2015-07-02 17:00 UTC
Twitter does not allows you to get all data for the followers of a random user, so we can not show all followers of a person, a loggedin user can see his followers/following on the map but we can do this maybe through scraping data we can display that and scrape it step by step since we don't have location data for a random person's followers we plot whoever we have the data from
and write down somewhere ("some users may not have location data associated with their account and will not show up on the map").So we save the data in loklak,As soon as we save it, others can search my followers/following too.Everything we take from twitter -> We need to save it in loklak.We need all the data from twitter to be saved in loklak!
This way people can also follow in future, who unfollows accounts at one point. this is what http://who.unfollowed.me/ does for example they save all followers/following

**Comment by Orbiter** [comment] 2015-07-06 13:25
I see several problems here:
- there are users with >100k followers, but when scraping users from the web page we only get 20 at once. That would make 5000 scraping-reloads for 100k followers.
- the data quickly becomes outdated. repeating a (large) scrape wil not be feasible
Both points cannot be solved easliy. If we consider this feature, then we must omit any complete expectation.

There are other obstactles:
- scraping is a lot of work
- creation of data strures as well
- it's unclear if re-loading of more-than-20 followers is possible. The problem is, that we not now know the reloading-address. If that address is computed by a JS function, then scraping becomes a real challenge.

I suggest a different approach: lets make an API for the followers/following and lets loklak_webclient fully depend on it. Then, as a first step, *only* get the information through the twitter API. If twitter rejects us, we can still create scrapers and databases.

**Comment by Orbiter** [comment] 2015-07-16 07:34
The rate limit of twitter is a big issue here! See https://dev.twitter.com/rest/reference/get/followers/list

Limitation | Attribute
--- | ---
Rate limited? | Yes
Requests / 15-min window (user auth) |15
Requests / 15-min window (app auth) | 30

With each request, only 20 followers can be retrieved. If a twitter client retrieves 300 followers, the function is disabled for 15 minutes. It also does not help to use a different authentication of the users we stored, because the *app* can only do 30 lookups during 15 minutes. This limitation means essentially that it is almost completely unusable for us.

The same applies to the loklak_webclient, there the same limitation would be applied.
However, implementing this now in the back-end would at least give a caching for already loaded followers.

**Comment by mariobehling** [comment] 2015-07-16 08:09
I wonder how other services like tweepsmap.com and who.unfolled.me are doing it. They have the data within a few seconds after you registered.

**Comment by Orbiter** [comment] 2015-07-16 09:53
It may depend on the size of the follower list. I also found a way to get much more follower IDs (instead of full user records), there you can get 15 * 5000 IDs. If you already have users assigned to such IDs, you can get more info. This is still limitied to 75000 followers which the service can take from twitter within 15 Minutes (not only for one user of the service, for all of them!)

**Comment by Orbiter** [comment] 2015-07-16 09:59
once the IDs are received, it is possible to get 100 users at once with https://dev.twitter.com/rest/reference/get/users/lookup
This can also be repeated only 15 times within 15 minutes. That means you get at most 1400 User accounts at once - once reqeust gives you 5000 ids and from them you can take 100 each 14 times. Then the API throws an exception and you have to wait.

**Comment by Orbiter** [comment] 2015-07-16 23:20
One part of the job is done, loklak_server now takes the user profile data from twitter and stores it.
Try:
```
http://localhost:9000/api/account.json?screen_name=mariobehling
```
This will give you extensive data about the account. To retrieve this data, first the OAuth key of the user is used. If this fails, the loklak app OAuth key is used.

This does not yet provide follower data, will provide this soon as well...

**Comment by Orbiter** [comment] 2015-08-03 10:29
This has been implemented with the `user.json` servlet, see http://loklak.org/api/user.json?screen_name=loklak_app

**Closed by Orbiter** 2015-08-03 10:29 UTC
Labels: blocker for loklak_webclient, enhancement
