### ISSUE TITLE
Error 500 when entering Mario as a keyword

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#1] opened 2015-03-29 13:53 UTC
http://www.loklak.org/api/search.rss?q=Mario

HTTP ERROR: 500

Problem accessing /api/search.rss. Reason:

    java.lang.ArrayIndexOutOfBoundsException

Powered by Jetty://

**Comment by Orbiter** [comment] 2015-03-30 16:41
Without further details (i.e. a stack trace) it is very difficult to find the source of this problem. I tried but failed. I strongly believe that this is not connected to the keyword Marion but was just bad luck. However, this is definitely a bug. Must be monitored when appears the next time.

**Comment by sudheesh001** [comment] 2015-03-31 12:14
I had a similar error which I had filed (something [similar](https://github.com/Orbiter/loklak/issues/6)), the main problem I realised when it came to this issue of hitting 500s randomly and then being unable to reproduce is mostly restricted to the first query after starting the server. I have noticed the current behaviour as follows
1. run `bin/start.sh` to start the server on `9100` port
2. Open up any web browser and wait for a while, As you are waiting, the page automatically shows up at `localhost:9100`, before this page is obtained if any search operation is performed like `GET /api/search.rss?q=Mario` or `api/search.json?q=Mario` it ends up hitting a 500 error.

I think its because it takes that little amount of time so that the server starts up, once its running, the 500 error never appears.

Leaving that, I guess its just plain bad luck !

**Comment by smokingwheels** [comment] 2015-04-02 05:08
I think its because I was pulling 150 RSS operation every 10 min with yacy from loklak.org.
I have droped the RSS querie back to approx 100 every 10 mins.

I am trying to reproduce on one of mine, its running very slow but no sign of the 500 error. The loklak and yacy server are on the same machine.

Shortly I will have another PC locally and will run a similar load test where other PC's pull info off it.

**Comment by Orbiter** [comment] 2015-04-18 08:59
I believe this was caused by bad utf-8 encodings causing bad xml. This should be fixed meanwhile.

**Closed by Orbiter** 2015-04-18 08:59 UTC
