### ISSUE TITLE
Search for tweet with a certain ID fails randomly

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_server#119] opened 2015-08-22 10:26 UTC
Success request: http://loklak.org/api/search.json?q=id:635018652664729601

Failure request: http://loklak.org/api/search.json?q=id:631929433352478720
(corresponding tweet: https://twitter.com/ReettaRaty/status/631929433352478720)

The different between the success result & failure result tweet is not clear, I tried a few difference cases it's not because one is older than another and vice versa. Defining explicitly `source=twitter` didn't help (as well as other values)

This is also a blocker of https://github.com/loklak/loklak_webclient/issues/453#issuecomment-133333536

**Comment by Orbiter** [comment] 2015-08-31 22:05
I first tried the given links and was able to reconstruct that issue. One possible cause could be, that the corresponding tweet was not already present in the loklak search index. Then there would not be a way to get the tweet as result because there is no search request to twitter to search for a specific ID.

To test this thesis, the tweet in the given example was searched using the quoted fulltext ("täs just kuultiin poliitikkojen arvailua siitä, millaista on. Mut joo kymmenettuhannet varsinaiset tietää hyvin iteki."). This resulted in one hit and after this the scraped result was in the search index as well. Searching then for the given ID was also successfull.

This is therefore not a bug.

The issue on the loklak_webclient side is at https://github.com/loklak/loklak_webclient/issues/453
To solve this, a support from the back-end is needed and this one is one of the proposed solutions. An alternative solution would be https://github.com/loklak/loklak_server/issues/94
I will close this issue in favor of https://github.com/loklak/loklak_server/issues/94 since this is not a bug and probably the worse soltion if a scraper would take the data for each requested ID

**Closed by Orbiter** 2015-08-31 22:05 UTC
Labels: bug
