### ISSUE TITLE
Implement the collection of photos and add this feature as an option in the config/settings

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#954] opened 2017-01-07 14:26 UTC
loklak currently does not collect images from its sources.

Please implement the collection and add it as a configurable option, that can be switched on or off in the config/settings.

**Comment by uttu357** [comment] 2017-03-20 19:51
Duplicate of #1026. Can be closed.

**Closed** 2017-05-07 20:59 UTC
Labels: enhancement, feature
